# 核心任务
- name: MongoDB
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: True

  vars_files:
    - vars/main.yml

  vars_prompt:
    - name: 'mongodb_version_selection'
      prompt: "\nPlease choose the number for MongoDB version [ 1/2/3/4] \n\n
      1: MongoDB3.0(not support Ubuntu18 and AmazonLinux2)\n
      2: MongoDB3.2(not support Ubuntu18 and AmazonLinux2)\n
      3: MongoDB3.3(not support Ubuntu18 and AmazonLinux2)\n
      4: MongoDB3.4(not support Ubuntu18 and AmazonLinux2)\n
      5: MongoDB3.5(not support Ubuntu18 and AmazonLinux2)\n
      6: MongoDB3.6(not support Ubuntu18 and AmazonLinux2)\n
      7: MongoDB3.7(not support Ubuntu18)\n
      8: MongoDB4.0\n
      9: MongoDB4.2\n"
      private: no
      default: 4
      
    - name: 'mongodb_server_selection'
      prompt: "\nMongoDB Community or MongoDB Enterprise? [ 1/2 ] \n\n
      1: MongoDB Community\n
      2: MongoDB Enterprise\n"
      private: no
      default: 1
    
    - name: 'mongodb_remote_selection'
      prompt: "\nDo you want to enable MongoDB remote connection? [ 1/2 ] \n\n
      1: Yes\n
      2: No\n"
      private: no
      default: 1
      
    - name: 'mongodb_authentication_selection'
      prompt: "\nDo you want to enable authentication (add administrator user) for MongoDB? [ 1/2 ] \n\n
      1: Yes\n
      2: No\n"
      private: no
      default: 1

    - name: 'mongodb_adminmongo_selection'
      prompt: "\nDo you want to install adminMongo of Docker? [ 1/2 ] \n\n
      1: Yes\n
      2: No\n"
      private: no
      default: 1

  vars:
    mongodb_version_select:
      '1': '3.0'
      '2': '3.2'
      '3': '3.3'
      '4': '3.4'
      '5': '3.5'
      '6': '3.6'
      '7': '3.7'
      '8': '4.0'
      '9': '4.2'
      
    mongodb_server_select:
      '1': 'community'
      '2': 'enterprise'
   
    mongodb_remote_select:
      '1': True
      'y': True
      '2': False
      'n': False
    
    mongodb_authentication_select:
      '1': True
      'y': True
      '2': False
      'n': False
      
    mongodb_adminmongo_select:
      '1': True
      'y': True
      '2': False
      'n': False
      
    mongodb_version: "{{mongodb_version_select[mongodb_version_selection]}}" 
    mongodb_server: "{{mongodb_server_select[mongodb_server_selection]}}" 
    mongodb_remote: "{{mongodb_remote:_select[mongodb_remote:_selection]}}" 
    mongodb_authentication: "{{mongodb_authentication_select[mongodb_authentication_selection]}}" 
    mongodb_adminmongo: "{{mongodb_adminmongo_select[mongodb_adminmongo_selection]}}" 
  
  roles:
   - {role: role_common, tags: "role_common"}   
   - {role: role_cloud, tags: "role_cloud"}
   - {role: role_mongodb, tags: "role_mongodb"}
   - {role: role_docker, tags: "role_docker", when: mongodb_adminmongo}
   - {role: role_init_password, tags: "role_init_password"}
   - {role: role_preend, tags: "role_preend"}
   - {role: role_end, tags: "role_end"} 
